### ISSUE TITLE
filtering with cherche

### ISSUE THREAD

**Issue by Balogunolalere** [raphaelsty/cherche#11]
hi, please is it possible to filter the search

**Comment by raphaelsty** [comment]
Hi @Balogunolalere, Cherche do no provide utilities to filter the search on specific fiels but you can filter the search using ElasticSearch retriever: [Section: write your own query](https://raphaelsty.github.io/cherche/retrieve/elastic/).

**Comment by Balogunolalere** [comment]
thanks alot.
