### ISSUE TITLE
is this just build new index and skip the index before?

### ISSUE THREAD

**Issue by fivejjs** [raphaelsty/cherche#19]
https://github.com/raphaelsty/cherche/blob/6aabe70853d2486ee1972e1689290fdce8b72587/cherche/index/faiss_index.py#L107C13-L107C64

**Comment by raphaelsty** [comment]
Hi @fivejjs, the function you are linking check if there is already a Faiss Index. It not, it create one. If there is a Faiss Index, this function do nothing
